### ISSUE TITLE
Bridge does not work anymore with HSAC 3.0.0

### ISSUE THREAD

**Issue by lennyg1** [fhoeben/hsac-xebium-bridge#11]
Probably due to the switch to Selenium 3.4, the HSAC Xebium bridge fails to work with HSAC 3.0.0.

The error is; java.lang.NoClassDefFoundError: com/thoughtworks/selenium/CommandProcessor

The error occurs on a testpage when loading the HsacBasicSeleniumDriverFixture.

At the moment I still use the HSAC Xebium bridge for some older regressionsuites I run, and in the rare case that I need to push Javascript to the browser or where BrowserTest can't find a specific element.

**Comment by fhoeben** [comment]
Yes I believe this will be caused by the upgrade to Selenium 3.x. Maybe it can be fixed by adding a couple of dependencies. But maybe it is not fixable as Selenium wants to move away from the approach to browser automation it used in its 1.x releases. This is the approach that Xebium relies on.

I no longer have any test projects using Xebium. Do you have a small sample test-page that I can use to see whether I can make the bridge function again?

**Comment by lennyg1** [comment]
As far as I know Xebium works with the new-ish webdriver system. Because I can actually use Selenium 3.4 GRID with Xebium. I've been using that until I switched to HSAC 2.x with the HSAC-Xebium bridge. While I am in the process of rewriting the tests, I usually just test with the Xebium example suites (XebiumTemplate) as a quick test, where I replace the default suitesetup with the one supplied below.

All this seems like is a missing class that's been removed in Selenium 3.4. That was rarely in use to begin with.

```
|import                                  |
|nl.hsac.fitnesse.fixture                |
|nl.hsac.fitnesse.fixture.slim           |
|nl.hsac.fitnesse.fixture.slim.web       |
|nl.hsac.fitnesse.fixture.slim.web.xebium|

|script              |selenium driver setup                              |
|connect to driver at|${grid}|with capabilities|!{browserName:${browser}}|
|show                |driver description                                 |

|library                                                                |
|nl.hsac.fitnesse.fixture.slim.web.xebium.HsacBasicSeleniumDriverFixture|
|stop test fixture                                                      |
|browser test                                                           |

|script                          |
|set browser size to maximum     |
|note  |seconds before timeout|60|

|script                                      |
|set timeout to|${seltimeout}                |
|start browser |${browser}|on url|${baseurl} |
```

**Comment by fhoeben** [comment]
Should be addressed in 0.6.0 release
